# Generated by Django 2.2.1 on 2019-05-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='available',
            field=models.CharField(choices=[('Daily', 'daily'), ('Weekly', 'weekly'), ('Seasonal', 'seasonal')], max_length=75),
        ),
    ]
