# Generated by Django 2.2.1 on 2019-05-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_auto_20190516_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='base',
            field=models.CharField(choices=[('Chocolate', 'chocolate'), ('Vanilla', 'vanilla')], max_length=75),
        ),
    ]
