# Generated by Django 2.2.1 on 2019-05-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0006_auto_20190516_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='featured',
        ),
    ]
