# Generated by Django 2.2.1 on 2019-05-16 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0009_remove_menu_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='featured',
            field=models.BooleanField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
