# Generated by Django 2.2.1 on 2019-05-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0010_menu_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='featured',
        ),
    ]
