# Generated by Django 2.2.1 on 2019-05-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0012_menu_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='available',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Seasonal', 'Seasonal')], max_length=75),
        ),
        migrations.AlterField(
            model_name='menu',
            name='base',
            field=models.CharField(choices=[('Vanilla', 'Vanilla'), ('Chocolate', 'Chocolate')], max_length=75),
        ),
    ]
