# Generated by Django 2.2.1 on 2019-05-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0014_menu_model_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='model_pic',
            field=models.CharField(max_length=255),
        ),
    ]
